package PdfGenerator;

import java.io.File;
import java.io.FileOutputStream;
import java.util.Date;

import javax.json.JsonArray;
import javax.json.JsonArrayBuilder;
import javax.json.JsonObject;
import javax.servlet.ServletContext;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;


public class GeneratePage {
	Font font = FontFactory.getFont(FontFactory.COURIER, 16, BaseColor.BLACK);
	Font header = FontFactory.getFont(FontFactory.COURIER_BOLD, 18, BaseColor.BLACK);
	Paragraph preface = new Paragraph();
	public Document main(JsonArray array, String userid){
		System.out.println(userid);
		
		Document document = new Document();
		JsonObject object = null;
		for (int i =0 ; i< array.size();i++){
			object = array.getJsonObject(i);
			
		}
		try{
			File file = File.createTempFile("contract_" + userid, ".pdf");
			PdfWriter.getInstance(document, new FileOutputStream("." + file.getPath()));
			
			document.open();
			
			addTitlePage(document);
			
			document.add(Chunk.NEWLINE);
			document.add(new Paragraph("User information:",header));
			document.add(new Paragraph("User identification number: " + userid));
			document.add(new Paragraph("Firstname: " + object.getJsonString("firstname").toString()));
			document.add(new Paragraph("Lastname: " + object.getJsonString("lastname").toString()));
			document.add(new Paragraph("Phonenumber: " + object.getJsonString("phonenumber").toString()));
			document.add(new Paragraph("Date of birth: " + object.getJsonString("dateOfBirth").toString()));
			document.add(Chunk.NEWLINE);
			document.add(new Paragraph("Adres information",header));
			document.add(new Paragraph("Country code: " + object.getJsonString("country").toString()));
			document.add(new Paragraph("Street: " + object.getJsonString("street").toString()));
			document.add(new Paragraph("Number: " + object.getJsonString("number").toString()));
			document.add(new Paragraph("Postalcode: "  +object.getJsonString("postalcode").toString()));
			document.add(new Paragraph("Description: " + object.getJsonString("adresDescription").toString()));
			document.add(new Paragraph("Gps location: " + object.getJsonString("location").toString()));
			document.add(Chunk.NEWLINE);
			document.add(new Paragraph("Loan information",header));
			document.add(new Paragraph("Loantype: " + object.getJsonString("loantype").toString()));
			document.add(new Paragraph("Amount: " + object.getJsonString("amount").toString()));
			document.add(new Paragraph("Start date: " + object.getJsonString("startDate").toString()));
			document.add(new Paragraph("Duration: " + object.getJsonString("duration").toString()));
			document.add(new Paragraph("Loan description: " + object.getJsonString("loandescription").toString()));
			
			
			document.close();
			return document;
		}
		catch(Exception e){
			System.out.println(e);
			return document;
		}
	}

	public void addTitlePage(Document document) 
		 throws DocumentException {
			Image img = null;
			try{
				//img = Image.getInstance("/../../src/main/webapp/img/logo.png");
				document.add(img);
			}catch(Exception e){
				System.out.println(e);
			}
			
		        // We add one empty line
		        addEmptyLine(preface, 1);
		        // Lets write a big header
		        preface.add(new Paragraph("Contract", font));

		        addEmptyLine(preface, 1);
		        // Will create: Report generated by: _name, _date
		        preface.add(new Paragraph(
		                "Contract generated by: " + System.getProperty("user.name") + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
		                font));
		        addEmptyLine(preface, 3);
		        preface.add(new Paragraph(
		                "This contract describes the terms of license of a microfinancing given by Bundle",
		                font));

		        addEmptyLine(preface, 8);

		        preface.add(new Paragraph(
		                "This contract is a strict and binding for as long as this contract as valid. If in any case you refuse to follow this contract a fine could and will be given.",
		                font));

		        document.add(preface);
		        // Start a new page
		        document.newPage();
		
	}

	public void addEmptyLine(Paragraph paragraph, int number) {
		 for (int i = 0; i < number; i++) {
	            paragraph.add(new Paragraph(" "));
	        }
		
	}
}
